### ISSUE TITLE
How is the resource assignment done for unknown workload requirements

### ISSUE THREAD

**Issue by hodiapa** [twosigma/Cook#100]
If a given simulation is unknown, eg: if it is not known how long it will take and how much resources it will take? how is the resource allocation done and also the load balancing?

**Comment by leifwalsh** [comment]
Cook is ultimately a reservation-based scheduler.  Users need to specify their resource needs up front, which is likely an estimation, and more likely to be an overestimation.  Cook does not try to make any duration-based decisions, so the length of a job is irrelevant.  With sufficient historical data, it may be possible to make resource requirement suggestions based on domain-specific job characteristics, and it may also be possible to estimate job runtime in order to kill (and schedule retries for) jobs which are failing to meet their likely runtime limits because of external failure factors.

Resource allocation is done using Dynamic Cumulative Resource Share analysis, described in [this talk](https://www.youtube.com/watch?v=BkBMYUe76oI) by @icexelloss, with a basis in [this paper](https://www.cs.berkeley.edu/~alig/papers/drf.pdf).

Load balancing is pretty much outside the scope of Cook.  Cook aims to allocate resources to users.  Users may query for the placement of their running jobs and perform load balancing with an external system, if they're service-providing tasks.

**Comment by DaoWen** [comment]
Closing this question since it's been inactive for 2+ years.
