### ISSUE TITLE
Cook API attempts to log Kerberos user even if configured auth isn't Kerberos

### ISSUE THREAD

**Issue by mforsyth** [twosigma/Cook#123]
This causes 500 errors on API requests when not using Kerberos. 

This was introduced here:
bb2b63228566400c423925e4ac30f838ebddf052

Should leave the same access logging behavior in,  just do it only when it's actually configured to use Kerberos.

**Comment by wyegelwel** [comment]
[Ring_ Stacktrace.pdf](https://github.com/twosigma/Cook/files/225053/Ring_.Stacktrace.pdf)

Attached the error message when this occurs. It appears that this stackoverflow discusses the issue: http://stackoverflow.com/questions/15029148/tomcat-fails-to-authenticate-using-spnego-cannot-locate-default-realm

Perhaps the best thing to do is change to use a different auth method since it is only used as a shim  to get a user associated with the request.

**Comment by wyegelwel** [comment]
This is no longer an issue following the merging of PR #125
