### ISSUE TITLE
Provide ability to update Priority of a Waiting job.

### ISSUE THREAD

**Issue by tnn1t1s** [twosigma/Cook#50]
Users would like programmatic ability to sort the queue. More generally, can we provide the ability to update any mutable property of a job via an UPDATE method.

**Comment by dgrnbrg** [comment]
What properties of the job should be mutable? Currently, none of them are definitely safe to mutate--instead, the better type of design for this sort of system would be to provide a clone + cancel API, which would create new jobs based on an existing job's template, with some properties changed.

This will keep the data model mostly immutable, which will make it easier to continue to avoid consistency bugs.

**Comment by tnn1t1s** [comment]
IMO priority is mutable. after discussion over here, i don't think other properties should be mutable e.g name. 

>>  the better type of design for this sort of system would be to provide a clone + cancel API,

this would be result in a different user experience than updating the queue in place. in the use case I have in mind, which I can explain 1/1, this experience delta would probably be significant.

**Comment by dgrnbrg** [comment]
Could you write it up here? It's much better to have clearly written design discussions.

**Comment by dgrnbrg** [comment]
Check out PR #52 and these docs: https://github.com/twosigma/Cook/blob/clone-api/scheduler/docs/scheduler-rest-api.asc#updatemodifyclone-a-job

This is what I have in mind, since it gives you almost the same user experience (you can update priorities of running jobs, restart jobs w/ more or fewer CPUs or memory, and change the user a job is running as).

Does this seem to solve your problems?

**Comment by tnn1t1s** [comment]
I don't understand what the impact of changing a running job would be. It's already been scheduled. For queued jobs, I think it's important to retain the submission time and any other properties of the job that are considered in the scheduling order. In the case of priority, cancel/resubmit is not the same as update in place.

**Comment by leifwalsh** [comment]
I thought the point of datomic was that updates preserve history for you so you can ignore this problem in the application. 



-- 
Cheers,
Leif

**Comment by dgrnbrg** [comment]
@tnn1t1s We don't treat waiting or running jobs any differently in our prioritization algorithms. One of our goals in the next few weeks is to improve the time to schedule large workloads, such as 1000 worker Spark jobs. This will be done by making some of our current batch scheduling algorithms incremental. Because of this change, treating waiting and running jobs differently isn't feasible. Furthermore, the submission time doesn't matter for scheduling order if you're changing its priority, since priority strictly dominates. For example, if I had 1000 jobs waiting at priority 50, and I submit a job at priority 51 a day later, the priority 51 job will run immediately, and maybe even preempt some of the running priority 50 jobs. That's why cancel/resubmit is semantically the same as update in place, but it allows our data model to remain eventually consistent across slaves during partial network failures.

@leifwalsh Datomic's historical view is really intended for audit trails and post-fact debugging operations.

**Comment by tnn1t1s** [comment]
>>  For example, if I had 1000 jobs waiting at priority 50, and I submit a job at priority 51 a day later, the priority 51 job will run immediately

Unless, there are already a large set of queued jobs with priority 51.

in the case I'm thinking of, the user submits a set S1 of N jobs with Priority X then later submits another set, S2, of M jobs with Priority X, and so on, and where N & M are very large. 

After some time, a subset of jobs in set S1 and S2 complete. The results of these sets are then used to update an opinion on the priority of other jobs related to the completed subset.  This is then repeated for the set S2, and so forth. 

In this case, the user wants to avoid complexity on the client application. They'd like to use the same P values (e.g. High, Low) across all job sets and then have sort order be considered in scheduling in case of a tie. 

As I understand it, the clone and resubmit solution would not behave the same as updating the priority in a transaction. I certainly understand the concerns about adding complexity but I'm equally concerned about pushing that to the client.

**Comment by dgrnbrg** [comment]
That is very complicated. Essentially, that's just asking for the ability to have even finer grain over the per-user queue. However, there's a few issues:

- The fact that we sort by time is actually meant to provide some semblence of FIFO and temporal clustering
- When bumping the priority, you still keep the temporal clustering with the data model I'm suggesting
- But you don't keep the fifo--or do you? Since the whole point was to change the priority, the order is captured by the priority!

A user would only want to bump the priority of jobs if they're waiting for them. Thus, the client application should have 3 priorities--High, Low, and Rush. The user can select to "rush" the jobs they need immediately, and still get the semantics they want.

Our syntax isn't anywhere close to mirroring this client application. We have 100 priority levels, and it has 2. Luckily, when a user intervenes, they can map that to High++, which will give the exact same result, but without the complexity.

Second reason we can't do it: if we copied the time, that'd break all our analytics, since the job would look like it was submitted yesterday but actually was submitted today, and just lied about the submission time in order to change the tiebreaker in the job sorter. It should instead use the user-exposed tiebreaker--the priority--and set it to what priority it actually wants, not an arbritrary priority that doesn't accomplish the user's goals (that's high vs. high++)

**Comment by dgrnbrg** [comment]
One other thing--in terms of client complexity, we already require quite a bit of sophistication for ID generation and persistence and domain mapping. The way to solve this is to provide documentation and guidance on how to use this API & priorities for common scenarios, and offer advice on situations like the one you described above. The fundamental sticking point in your example above is that the user submitted some jobs with LOW priority, and they want them to run first, but there's earlier HIGH priority jobs before them in the queue. This is exactly why we made so many priority levels, and why explaining to the user that they'd need 3 levels--LOW, HIGH, and INTERACTIVE/URGENT--is the right solution.

**Comment by tnn1t1s** [comment]
I proposed a similar solution to the user prior to this discussion. I believe the 3 level strategy approximates the behavior the user expects while maintaining the properties of Cook we want. An N level strategy can provide the exact requirements. In discussion internally, we've come up with a third solution that doesn't leverage priorities at all. Instead, deferring job scheduling until early results are already available. This pushes the algo logic to the client, where, as I think you argue successfully, it logically belongs.

**Comment by dgrnbrg** [comment]
What are you talking about? We already have an N level scheduler.

**Comment by tnn1t1s** [comment]
>> An N level strategy can provide the exact requirements.

right, but the user didn't want to deal with managing N levels across multiple sets of jobs. anyway, like I said, there's an alternate solution.

**Comment by dgrnbrg** [comment]
So the issue's resolved fully? Is there a compelling need for the clone API?

**Comment by tnn1t1s** [comment]
not in this case, we've found a better solution on the client side.

**Comment by dgrnbrg** [comment]
Great. I'll close this issue, as we have the Clone PR, which I think is still the right general solution for "changing" jobs.
