### ISSUE TITLE
Add support for other databases

### ISSUE THREAD

**Issue by dgrnbrg** [twosigma/Cook#7]
The first step here is determining the types of queries we do. This issue should be updated with the current list:
- Find all jobs of a particular status
- Find all non-terminal instances
- Query a particular job or instance by ID

The status-related queries require second indices, but we could change instance IDs to be `[jobid instanceid]` pairs, so that we only need to implement lookup by job id, and then we'd just store a "document" with the full job & instance state.

Still to be analyzed:
- What's the impact on the metrics reporter's user stats?
- How critical are the transaction functions? Could we change them to run locally, or all be CAS-based?
- Can we refactor the use of the Datomic txn log tailer to be totally local, core.async, and per-process?

**Comment by reachbach** [comment]
A database that has wider production deployments is a must-have for my company to consider using the cook framework in production. Datomic makes it a non-starter.

**Comment by zmalik** [comment]
Hi guys, 

Any updates on this? For us, it's also a non-starter with Datomic. 

Would be happy to help in that case, but need to know if other users also still want it.

**Comment by DaoWen** [comment]
Hi @zmalik ,

I think it would be helpful to the overall discussion if you could clarify why Datomic is a non-starter for your organization, as well as what alternatives you'd find acceptable and why.

**Comment by zmalik** [comment]
Yep, makes sense! 

We have more than 10k daily jobs. And we are evaluating different Mesos frameworks to be our "runner" framework to move away from our current framework. From all the frameworks we have seen Cook is the one that fits more to our requirements.

Still, we aren't happy to be locked with a paid solution. Or at least, to this paid solution which we are currently not using in our company. 

We aren't expecting to somebody else implement the alternative. But we would like to know your opinion about integrating another distributed database alternative before making a decision. I don't want to push the team towards a solution that at some point we may need to get away from it.

**Comment by pschorf** [comment]
We've also looked into moving away from Datomic as well, but shied away based on the overall cost of implementing the change. I think it's something we'll be looking at next year as well, but the code is very tightly coupled to Datomic as it is, so I'd anticipate the change being fairly extensive.

**Comment by DaoWen** [comment]
@zmalik - Unfortunately, the Dataomic API is very viral. The queries only pop up in a few places in Cook, but the [entity objects](http://docs.datomic.com/entities.html) are strewn throughout the whole codebase. Switching to a different database API would require tracking down every *get* operation on an entity in our code, and either refactoring all of the initial queries to pre-fetch that data, or adding additional "lazy" queries elsewhere to fetch the other data on-demand. Like @pschorf said above, the migration away from Datomic would be a very large effort.

If you want to evaluate Cook, you could try it with a free [Dataomic Pro Starter](http://www.datomic.com/get-datomic.html) license. You'd be stuck with paying for an annual license after the first year (assuming you want support and updates), but it might still be worth exploring.

Just out of curiosity, what other schedulers are you looking at?

**Comment by zmalik** [comment]
Thank you, guys! for such a quick and precise answer!

@DaoWen we are just looking at other available frameworks that have the ability to schedule tasks and are able to scale without pain, not leaving orphan tasks etc or causing resource starvation due to poor allocation of tasks. Having support for maintenance primitives (for autoscaling) and Labels etc (for reporting/exposing tasks). But these minor features aren't blockers at all as we can add those features easily. Our main concern is that where the queue of jobs is saved and how quick a framework can fetch the next job to schedule(ordered by custom priority) in the queue and match an offer for it and schedule.   

What we don't want to develop is, yet another Mesos framework, and maybe just help some existing open source solution and give it proteins to fulfil our needs.

**Comment by alanbover** [comment]
Maybe I can extend a little bit more about what we are looking for.
In our company we suffer a lot about technology fragmentation (this affects also task schedulers). Our current solution for batch jobs (Chronos) doesn't allow us to properly integrate with other solutions people are already using, as they already have it's own scheduler (like airflow). 

We are looking for a solution that provides the "minimum" runtime logic, so a run-once based framework with a single persistent queue, where we can set our own task prioritization function.

So far we have looked into singularity (too complex for what we need), Eremetic (missing some functionalities that we would have to build on-top) and Cook.

**Comment by DaoWen** [comment]
The current feeling is that we're too tightly coupled to Datomic, making the task of supporting another database a massive refactoring effort.

**Comment by dgrnbrg** [comment]
I did analyze what it’s take to move off of datomic a year or 2 ago, and it
wasn’t that bad—it just required making a facade over another db to get the
backrefs in the entity api to work. That is, unless there’s more querying
now than before.

**Comment by DaoWen** [comment]
@dgrnbrg - Thanks! I assumed the Datomic API usage in Cook has become more complex since this issue was originally opened (we're definitely doing more via the entity lookups than just backrefs now)—but maybe it wouldn't be as bad as we were thinking. Do you know of any other projects that support Datomic and some other database API? My impression was that, if we're going to support another database (e.g., Cassandra) directly, that basically means we're dumping Datomic altogether.

In either case, I'm closing this issue for now since we have no current plans to address this, and leaving it open seems to be giving people false hopes...

**Comment by wyegelwel** [comment]
I tried spending a few hours building a facade in front of sql to do
exactly what @dgrnbrg described about a year ago. You can see it:
https://githib.com/wyegelwel/datomic-sql

I imagine if one spent a few weeks on it they could get a large portion of
datomic entities and queries working as expected. Unclear how long it would
take to get all cook usage though.

Getting inserts and updates to work correctly would be an additional
challenge since we currently rely pretty heavily on transaction functions.
For each database we would need to correctly replicate that logic.

**Comment by dgrnbrg** [comment]
Yeah, I agree. I'd probably rework the system to use an eventually consistent KV store like Cassandra or DynamoDB, so that it'd be easier to host on standard infra. Then, you could drop datomic altogether. The KV stores have many features that make them nice for Cook, since Cook rarely needs to do anything but pointwise lookups and whole table dumps.
