### ISSUE TITLE
Transient test failures - ValueError: signal only works in main thread

### ISSUE THREAD

**Issue by scrosby** [twosigma/Cook#749]
Why is this dying in startup? Something in the integration test framework? Its literally dying in the import statements:

https://travis-ci.org/twosigma/Cook/jobs/350392763

> tests/test_config.py:6: in <module>
>     import cook.config as cc
> cook/config.py:6: in <module>
>     from pymesos.utils import parse_duration
> ../../../../.local/lib/python3.6/site-packages/pymesos/__init__.py:2: in <module>
>     from .scheduler import MesosSchedulerDriver
> ../../../../.local/lib/python3.6/site-packages/pymesos/scheduler.py:7: in <module>
>     from .process import Process
> ../../../../.local/lib/python3.6/site-packages/pymesos/process.py:33: in <module>
>     _prev_handler = signal.signal(signal.SIGINT, _handle_sigint)
> /opt/python/3.6.3/lib/python3.6/signal.py:47: in signal
>     handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
> E   ValueError: signal only works in main thread

**Comment by dposada** [comment]
@shamsimam I assigned to you since this seems to be executor-related

**Comment by DaoWen** [comment]
I've seen this before, and I think I discussed it with Shams. If I remember correctly, this can be fixed by forcing the import to happen on the main thread before any of the tests start running, which would trigger the module initialization in the main thread, and avoid these errors.

Adding the PyMesos import to [a conftest.py file](https://github.com/twosigma/Cook/blob/master/integration/tests/cook/conftest.py#L1-L4) might be sufficient to fix this.
